### ISSUE TITLE
Duplicate sources.list entry (Singular)

### ISSUE THREAD

**Issue by seijimtmt** [knxm/mathlibre#23]
The "singular-release" package provides "/etc/apt/sources.list.d/Singular.list" whose
content is same as that of "/etc/apt/sources.list.d/singular.list" (copied from
config/archives/singular.list.chroot at the chroot stage).

This causes a warning "Duplicate sources.list entry" while trying "apt-get update"
on the live system.

**Comment by knxm** [comment]
From stretch, singular was included to the official repository, sinular.list was removed.
